INSERT INTO topping (name) VALUES ('Pepperoni');
INSERT INTO topping (name) VALUES ('Mushroom');
INSERT INTO topping (name) VALUES ('Extra cheese');
INSERT INTO topping (name) VALUES ('Sausage');
INSERT INTO topping (name) VALUES ('Onion');
INSERT INTO topping (name) VALUES ('Black olives');
INSERT INTO topping (name) VALUES ('Green pepper');
INSERT INTO topping (name) VALUES ('Fresh garlic');
INSERT INTO topping (name) VALUES ('Tomato');
INSERT INTO topping (name) VALUES ('Fresh basil');